version: '2'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.1
        ports:
            - '9200:9200'
            - '9300:9300'
    kibana:
        image: docker.elastic.co/kibana/kibana:6.8.1
        ports:
            - '5601:5601'
        depends_on:
            -  elasticsearch
    logstash:
        image: docker.elastic.co/logstash/logstash:6.8.1
        ports:
            - '25826:25826'
        volumes:
            - $PWD/conf.d/:/etc/logstash/conf.d/
            - /var/log/:/var/log/
        command: logstash -f /etc/logstash/conf.d/logstash-spring.conf
        links: 
            - "elasticsearch:elasticsearch"
        depends_on:
            -  elasticsearch
